
services:
  postgres:
    image: postgres:15
    container_name: movie_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moviedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - movie_net

volumes:
  postgres_data:

networks:
  movie_net:
